apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Values.vflengine.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.vflengine.name }}
spec:
  replicas: {{ .Values.vflengine.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.vflengine.name }}
  serviceName: {{ .Release.Name }}-{{ .Values.vflengine.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.vflengine.name }}
    spec:
      containers:
      - name: {{ .Values.vflengine.name }}
        image: {{ (or .Values.vflengine.image.registry .Values.global.imageRegistry) }}{{ .Values.vflengine.image.repository }}:{{ .Values.vflengine.image.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}


        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Running VFL in mode: {{ .Values.vflengine.role }}"
            chmod +x /workspace/run.sh
            /workspace/run.sh {{ .Values.vflengine.role }}

        ports:
        {{- if eq .Values.vflengine.role "host" }}
        - containerPort: {{ .Values.vflengine.host_ui_port }}
          name: host-ui
        - containerPort: {{ .Values.vflengine.host_port }}
          name: host-vfl
        {{- else if eq .Values.vflengine.role "guest" }}
        - containerPort: {{ .Values.vflengine.guest_ui_port }}
          name: guest-ui
        - containerPort: {{ .Values.vflengine.guest_port }}
          name: guest-vfl
        {{- end }}

        env:
        - name: ROLE
          value: {{ .Values.vflengine.role }}
        - name: HOST_IP
          value: {{ .Values.vflengine.host_ip }}
        - name: HOST_PORT
          value: {{ .Values.vflengine.host_port | quote }}
        - name: GUEST_IP
          value: {{ .Values.vflengine.guest_ip }}
        - name: GUEST_PORT
          value: {{ .Values.vflengine.guest_port | quote }}
        {{- if eq .Values.vflengine.role "host" }}
        - name: HOST_UI_PORT
          value: {{ .Values.vflengine.host_ui_port | quote }}
        {{- else if eq .Values.vflengine.role "guest" }}
        - name: GUEST_UI_PORT
          value: {{ .Values.vflengine.guest_ui_port | quote }}
        {{- end }}
        {{- with .Values.vflengine.extraEnvs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

        volumeMounts:
        - name: data
          mountPath: {{ .Values.vflengine.extraVolumeMounts.data }}
        - name: cache
          mountPath: {{ .Values.vflengine.extraVolumeMounts.cache }}
        {{- with .Values.vflengine.extraVolumeMounts.additional }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- include "common.volumes" . | nindent 6 }}

